### ISSUE TITLE
README review by group p02-yeast

### ISSUE THREAD

**Issue by sdemiriz** [hackseq/hs19-pop#2]
The topic of the project seems very interesting, and its applications could potentially be life saving. The description of the project, however, fails to clearly convey the full aim and potential of the project..

1. The awkward, difficult vocabulary of the description makes it difficult to follow the sentence flow. For example, the frequent use of the word "untoward" can be replaced by the simpler "adverse" etc.

2. The Motivation part is an exact copy of two sentences from the introductory paragraph, probably needs a rework or at least some alterations, possibly some details.

**Comment by veenaghorakavi** [comment]
Thank you!

**Comment by sdemiriz** [comment]
1. Loving the new introduction, a much clearer and concise paragraph that effectively delivers the necessary information to the reader.  However the line "When a patient is taking multiple medications, the patient will start to develop adverse and unforeseen health effects." seems to imply that any patient taking multiple drugs will be experiencing adverse effects, which does not seem wholly realistic, please correct me if I am in the wrong.

2. The Motivation section seems to have a lot a focus on the database querying and the chosen programming language side of the project rather than the motivation behind the project.  Probably needs its own section or just included in a more technical-oriented part of the readme.

3. Perhaps the Shiny website URL could also be included in the Introduction section for easier access and to catch the reader's eye when they visit the repository for the first time.

**Comment by veenaghorakavi** [comment]
We have taken into account feedback from @sedatDemiriz.  This issue will now be closed and can be reopened if Day 3 needs for this issue to be reopened.
