### ISSUE TITLE
Website UI redesign. 

### ISSUE THREAD

**Issue by veenaghorakavi** [hackseq/hs19-pop#5]
Note that the issue will have more information added to it as the hackathon progresses.  

Currently, the website looks like this:

<img width="1680" alt="Screen Shot 2019-10-19 at 9 43 24 AM" src="https://user-images.githubusercontent.com/16584441/67148502-0dd95680-f255-11e9-959f-4f73bb4041f3.png">

We should have a list of drug names and space to show the pathway information.  We should also have a colorful background. 

First step: 

- Suppress warnings. 
- Make sure drug names is current.

**Comment by maggie-fu** [comment]
Updated the UI
